apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: expandable-pvc
  namespace: exercise-4
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: expandable-sc
  resources:
    requests:
      storage: 1Gi