apiVersion: v1
kind: Namespace
metadata:
  name: exercise-3
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: retain-policy-sc
  namespace: exercise-3
provisioner: rancher.io/local-path
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: Immediate
parameters:
  type: pd-ssd